In [23]:
import pandas as pd
import numpy as np

D002_CSV_PATH = './d002.csv'

df = pd.read_csv(D002_CSV_PATH, encoding='cp949') #utf-8 or cp949

df

,청코드,선박키,입항연도,입항회수,업체코드,업체명,차항지코드1,차항지코드2,차항지명,적재톤수,...,출항예정일시,전출항지출항일시,전출항지코드1,전출항지코드2,전출항지명,입항일시,출항일시,양하톤수,선원수,전체승객수
0,20,9256391,2019,2,KMC2009,벤라인에이전시즈코리아주식회사,CN,DLC,DALIAN,6773.0,...,2019-10-18 15:00,2019-10-15 11:00,CN,DLC,DALIAN,2019-10-17 14:00,2019-10-18 14:00,6773.0,22.0,NaN
1,20,3FNH6,2019,3,BSC0003,(주)반도마리타임,CN,TAX,TAIXING,0.0,...,2019-10-16 09:00,2019-10-15 14:00,KR,USN,울산,2019-10-15 19:00,2019-10-16 10:00,0.0,16.0,NaN
2,20,DSPC5,2019,7,BSC2172,(주)진웅마리타임,KR,KPO,포항,4093.0,...,2019-10-15 18:00,2019-10-13 15:15,KR,KAN,광양,2019-10-14 06:00,2019-10-14 16:00,4093.0,10.0,NaN
3,20,960771,2019,42,BSK2533,유정해운(주),KR,OKP,옥포,0.0,...,2019-10-08 05:35,2019-09-26 10:05,KR,TYG,통영,2019-09-26 15:50,2019-10-08 05:35,0.0,4.0,0.0
4,20,9248227,2019,43,KMC0823,(주)팬스타,CN,SHD,SHIDAO PT,313.0,...,2019-06-27 12:00,2019-06-25 14:00,JP,NGO,"NAGOYA, AICHI",2019-06-26 20:00,2019-06-27 12:00,313.0,17.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272899,20,785874,2023,15,BSZ7572,금성호,KR,ZZZ,기타항,0.0,...,2023-09-12 12:00,2023-08-07 9:10,KR,ZZZ,기타항,2023-09-11 13:05,2023-09-19 15:25,0.0,1.0,0.0
272900,20,785874,2023,16,BSZ7572,금성호,KR,ZZZ,기타항,0.0,...,2023-11-04 12:00,2023-08-07 9:10,KR,ZZZ,기타항,2023-11-03 08:37,2023-12-04 08:54,0.0,1.0,0.0
272901,20,785874,2023,17,BSZ7572,금성호,KR,ZZZ,기타항,0.0,...,2023-12-05 12:00,2023-08-07 9:10,KR,ZZZ,기타항,2023-12-04 16:05,2023-12-04 16:06,0.0,1.0,0.0
272902,20,D9SV,2023,26,BSZ3389,해강선박,KR,ZZZ,기타항,0.0,...,2023-12-28 12:00,2023-12-18 13:10,KR,ZZZ,기타항,2023-12-27 08:55,2024-01-04 11:25,0.0,2.0,0.0
272903,20,31466,2022,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-12-26 00:00,2023-01-09 00:00,NaN,NaN,NaN

In [24]:
df.shape

(272904, 30)

In [25]:
df.dtypes

청코드           int64
선박키             str
입항연도          int64
입항회수          int64
업체코드            str
업체명             str
차항지코드1          str
차항지코드2          str
차항지명            str
적재톤수        float64
환적톤수        float64
위험물톤수       float64
진수결정톤수      float64
총톤수         float64
국제총톤수       float64
선박국적코드          str
선박국적명           str
선박종류        float64
선박종류명           str
선박명             str
출항예정일시          str
전출항지출항일시        str
전출항지코드1         str
전출항지코드2         str
전출항지명           str
입항일시            str
출항일시            str
양하톤수        float64
선원수         float64
전체승객수       float64
dtype: object

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 272904 entries, 0 to 272903
Data columns (total 30 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   청코드       272904 non-null  int64
 1   선박키       272904 non-null  str
 2   입항연도      272904 non-null  int64
 3   입항회수      272904 non-null  int64
 4   업체코드      271358 non-null  str
 5   업체명       271359 non-null  str
 6   차항지코드1    270646 non-null  str
 7   차항지코드2    270648 non-null  str
 8   차항지명      270648 non-null  str
 9   적재톤수      270645 non-null  float64
 10  환적톤수      270645 non-null  float64
 11  위험물톤수     270642 non-null  float64
 12  진수결정톤수    271211 non-null  float64
 13  총톤수       272467 non-null  float64
 14  국제총톤수     272331 non-null  float64
 15  선박국적코드    271156 non-null  str
 16  선박국적명     271156 non-null  str
 17  선박종류      272894 non-null  float64
 18  선박종류명     272894 non-null  str
 19  선박명       270853 non-null  str
 20  출항예정일시    270648 non-null  str
 21  전출항지출항일시  270648 non-null  str
 22  전출항지코드1   270645 non-null  str
 23  전출항지코드2   270648 non-null  str
 24  전출항지명     270648 non-null  str
 25  입항일시      272904 non-null  str
 26  출항일시      272904 non-null  str
 27  양하톤수      270644 non-null  float64
 28  선원수       270655 non-null  float64
 29  전체승객수     134168 non-null  float64
dtypes: float64(10), int64(3), str(17)
memory usage: 106.3 MB

In [27]:
pd.DataFrame({'자료형': df.dtypes.astype('str'),
              '비결측수': df.notna().sum(),
              '결측수': df.isna().sum(),
              '결측률(%)': df.isna().mean()*100,
              '고유값 수': df.nunique(dropna=True)})

              자료형    비결측수     결측수     결측률(%)   고유값 수
청코드         int64  272904       0   0.000000       1
선박키           str  272904       0   0.000000   15634
입항연도        int64  272904       0   0.000000       6
입항회수        int64  272904       0   0.000000     954
업체코드          str  271358    1546   0.566500    1252
업체명           str  271359    1545   0.566133    1268
차항지코드1        str  270646    2258   0.827397      98
차항지코드2        str  270648    2256   0.826664    1052
차항지명          str  270648    2256   0.826664    1126
적재톤수      float64  270645    2259   0.827764   38430
환적톤수      float64  270645    2259   0.827764   17185
위험물톤수     float64  270642    2262   0.828863    4096
진수결정톤수    float64  271211    1693   0.620365    7674
총톤수       float64  272467     437   0.160130    7206
국제총톤수     float64  272331     573   0.209964    7090
선박국적코드        str  271156    1748   0.640518     104
선박국적명         str  271156    1748   0.640518     104
선박종류      float64  272894      10   0.003664      50
선박종류명         str  272894      10   0.003664      50
선박명           str  270853    2051   0.751546   17047
출항예정일시        str  270648    2256   0.826664  160925
전출항지출항일시      str  270648    2256   0.826664  147437
전출항지코드1       str  270645    2259   0.827764      92
전출항지코드2       str  270648    2256   0.826664    1035
전출항지명         str  270648    2256   0.826664    1094
입항일시          str  272904       0   0.000000  220840
출항일시          str  272904       0   0.000000  222072
양하톤수      float64  270644    2260   0.828130   23233
선원수       float64  270655    2249   0.824099     431
전체승객수     float64  134168  138736  50.836924     729

In [28]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
청코드,272904.0,20.000000,0.000000,20.0,20.0,20.0,20.0,20.0
입항연도,272904.0,2021.471723,1.722922,2019.0,2020.0,2021.0,2023.0,2024.0
입항회수,272904.0,32.417740,66.355800,1.0,3.0,12.0,38.0,994.0
적재톤수,270645.0,7885.749667,224210.858739,0.0,0.0,270.0,3777.0,78494000.0
환적톤수,270645.0,1895.630406,25129.023256,0.0,0.0,0.0,184.0,999999.0
위험물톤수,270642.0,2584.363529,51004.264860,0.0,0.0,0.0,58.0,7380000.0
진수결정톤수,271211.0,14495.240137,31333.561978,0.0,317.0,1972.0,9948.0,236583.0
총톤수,272467.0,14286.851793,31308.407792,0.0,228.0,1757.0,9912.5,236583.0
국제총톤수,272331.0,14285.595803,31349.938189,0.0,51.0,1607.0,9946.0,236583.0
선박종류,272894.0,49.520308,17.873781,11.0,41.0,52.0,55.0,99.0
양하톤수,270644.0,2870.114145,116112.681025,0.0,0.0,0.0,2315.0,57835738.0
선원수,270655.0,13.758475,31.472948,0.0,5.0,12.0,19.0,3338.0
전체승객수,134168.0,13.425079,105.179995,0.0,0.0,0.0,0.0,5116.0

In [29]:
arrival = pd.to_datetime(df['입항일시'], errors='coerce')
arrival

0        2019-10-17 14:00:00
1        2019-10-15 19:00:00
2        2019-10-14 06:00:00
3        2019-09-26 15:50:00
4        2019-06-26 20:00:00
                 ...
272899   2023-09-11 13:05:00
272900   2023-11-03 08:37:00
272901   2023-12-04 16:05:00
272902   2023-12-27 08:55:00
272903   2022-12-26 00:00:00
Name: 입항일시, Length: 272904, dtype: datetime64[us]

In [30]:
departure = pd.to_datetime(df['출항일시'], errors='coerce')
departure

0        2019-10-18 14:00:00
1        2019-10-16 10:00:00
2        2019-10-14 16:00:00
3        2019-10-08 05:35:00
4        2019-06-27 12:00:00
                 ...
272899   2023-09-19 15:25:00
272900   2023-12-04 08:54:00
272901   2023-12-04 16:06:00
272902   2024-01-04 11:25:00
272903   2023-01-09 00:00:00
Name: 출항일시, Length: 272904, dtype: datetime64[us]

In [31]:
stay = (departure - arrival).dt.total_seconds()/3600
stay

0          24.000000
1          15.000000
2          10.000000
3         277.750000
4          16.000000
             ...
272899    194.333333
272900    744.283333
272901      0.016667
272902    194.500000
272903    336.000000
Length: 272904, dtype: float64

In [32]:
stay.describe()

count    272904.000000
mean        113.188220
std        3927.499566
min       -3362.966667
25%          10.250000
50%          20.908333
75%          47.783333
max      626602.250000
dtype: float64

In [34]:
valid = arrival.dt.year.eq(df['입항일시']) & stay.between(0,24*30)

stay[valid]

Series([], dtype: float64)

In [ ]:
date_cols = ['입항일시', '출항일시', '출항예정일시']

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

df['체류시간'] = (df['출항일시'] - df["입항일시"]).dt.total_seconds()/3600
df['출항지연시간'] = (df['출항일시'] - df["출항예정일시"]).dt.total_seconds()/3600

df[ ['체류시간', '출항지연시간']]

valid_stay = (df['입항일시'].dt.year.eq(df['입항연도'])
              & df['체류시간'].between(0,24*30))

valid_schedule = valid_stay & (df['출항예정일시'].between(df['입항일시'] - pd.Timedelta(days=1),
                                                    df['입항일시'] - pd.Timedelta(days=30))) #timedelta 오차범위

valid_stay.sum()

np.int64(267864)

In [45]:
pd.Series({
    '원본 행 수': len(df),
    '입항연도와 입항일시 연도 불일치': df['입항일시'].dt.year.ne(df['입항연도']).sum(),
    '음수 체류시간' : df['체류시간'].lt(0).sum(),
    '30일 초과': df['체류시간'].gt(24*30).sum(),
    '유효 체류시간 비율': valid_stay.mean()*100,
    '완전중복행' : df.duplicated().sum()
})

원본 행 수               272904.000000
입항연도와 입항일시 연도 불일치       214.000000
음수 체류시간                  19.000000
30일 초과                 4838.000000
유효 체류시간 비율               98.153197
완전중복행                     0.000000
dtype: float64

In [49]:
stay_quantile = df.loc[valid_stay, '체류시간'].quantile([0.5,0.75,0.9,0.95,0.99])

stay_quantile.index = ['중앙값', '75백분위', '90백분위', '95백분위', '99백분위']

stay_quantile

중앙값       20.333333
75백분위     45.116667
90백분위    118.111667
95백분위    214.000000
99백분위    481.000000
Name: 체류시간, dtype: float64

In [50]:
print(f'24시간 이내 출항 비율= {df.loc[valid_stay, '체류시간'].le(24).mean():.2f}')
print(f'7일 초과 체류 비율= {df.loc[valid_stay, '체류시간'].gt(24*7).mean():.2f}')

24시간 이내 출항 비율= 0.56
7일 초과 체류 비율= 0.07