In [1]:
import pandas as pd
import numpy as np

PRO02_CSV_PATH = '../pro02.csv'

df = pd.read_csv(PRO02_CSV_PATH, encoding='cp949') #utf-8 or cp949

df

        연도   월       연월 수출입구분 수출입구분설명        물동량
0     2003   2  2003-02    OT    수출환적  161074.50
1     2003  11  2003-11    IT    수입환적  170733.50
2     2006   1  2006-01    OT    수출환적  203348.25
3     2018   1  2018-01    OO      수출  413797.75
4     2013   6  2013-06    OO      수출  389650.25
...    ...  ..      ...   ...     ...        ...
1371  1996   1  1996-01    OO      수출  158518.00
1372  2001   6  2001-06    OO      수출  215325.25
1373  2001   9  2001-09    OT    수출환적  127883.00
1374  2004   1  2004-01    IT    수입환적  181137.50
1375  2005   3  2005-03    OT    수출환적  221527.25

[1376 rows x 6 columns]

In [2]:
pd.DataFrame({'자료형': df.dtypes.astype('str'),
              '비결측수': df.notna().sum(),
              '결측수': df.isna().sum(),
              '결측률(%)': df.isna().mean()*100,
              '고유값 수': df.nunique(dropna=True)})

             자료형  비결측수  결측수  결측률(%)  고유값 수
연도         int64  1376    0     0.0     34
월          int64  1376    0     0.0     12
연월           str  1376    0     0.0    398
수출입구분        str  1376    0     0.0      4
수출입구분설명      str  1376    0     0.0      4
물동량      float64  1376    0     0.0   1374

In [3]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
연도,1376.0,2009.982558,8.861585,1992.0,2003.00,2010.0,2017.2500,2025.0
월,1376.0,6.470930,3.464399,1.0,3.00,6.0,9.0000,12.0
물동량,1376.0,324784.228924,119286.831230,90300.0,222387.25,322195.5,420758.4375,635437.0

In [7]:
data_cols = ['연도', '수출입구분설명','물동량'] #원하는 수치만 선택

project = df[data_cols]

project

        연도 수출입구분설명        물동량
0     2003    수출환적  161074.50
1     2003    수입환적  170733.50
2     2006    수출환적  203348.25
3     2018      수출  413797.75
4     2013      수출  389650.25
...    ...     ...        ...
1371  1996      수출  158518.00
1372  2001      수출  215325.25
1373  2001    수출환적  127883.00
1374  2004    수입환적  181137.50
1375  2005    수출환적  221527.25

[1376 rows x 3 columns]

In [8]:
project['연도'].unique().tolist()

[2003,
 2006,
 2018,
 2013,
 2012,
 2017,
 2014,
 2015,
 2019,
 2022,
 1993,
 1995,
 2001,
 2004,
 2007,
 2010,
 2024,
 1994,
 1996,
 1997,
 1998,
 1999,
 2002,
 2005,
 2008,
 2025,
 2021,
 2009,
 2011,
 2016,
 1992,
 2020,
 2023,
 2000]

In [ ]:
# 수출환적 + 수입환적 → 환적으로 통합
temp = project.copy()
temp['구분'] = temp['수출입구분설명'].replace({
    '수출환적': '환적',
    '수입환적': '환적'
})

# 연도별 합계 계산
result_data = (
    temp.groupby(['연도', '구분'])['물동량']
        .sum()
        .unstack(fill_value=0)
        .reindex(columns=['수출', '수입', '환적'], fill_value=0)
        .reset_index()
)

result_data

구분    연도          수출          수입           환적
0   1992  1452695.00  1182679.00         0.00
1   1993  1540479.00  1400756.00         0.00
2   1994  1721176.00  1861341.00         0.00
3   1995  1912575.75  2177758.00         0.00
4   1996  2023501.00  2338534.00         0.00
5   1997  2196912.50  2614249.00         0.00
6   1998  2449246.75  2862064.75         0.00
7   1999  2471408.75  3189473.25         0.00
8   2000  2596600.75  3785717.00         0.00
9   2001  2558561.50  2571132.50   2943107.75
10  2002  2813530.75  2752573.25   3887984.00
11  2003  3061843.00  3095285.25   4251414.25
12  2004  3367405.00  3331520.00   4791840.00
13  2005  3315620.00  3348050.75   5179724.00
14  2006  3387969.25  3442844.00   5208295.25
15  2007  3693655.25  3756593.50   5811591.00
16  2008  3786886.25  3858055.75   5808188.00
17  2009  3327071.25  3280902.50   5372636.25
18  2010  3967771.75  3950133.25   6276690.75
19  2011  4372279.00  4460033.00   7352641.75
20  2012  4470118.25  4428513.25   8147545.75
21  2013  4512132.75  4425512.75   8748453.00
22  2014  4657638.75  4596289.75   9429354.75
23  2015  4650167.00  4713239.25  10105318.25
24  2016  4819338.75  4801126.50   9835826.00
25  2017  5159765.00  5055303.25  10278407.00
26  2018  5116408.50  5116858.50  11429309.00
27  2019  5162534.75  5191570.00  11637895.50
28  2020  4951252.75  4852616.75  12020125.50
29  2021  5225467.75  5207989.50  12272672.50
30  2022  5178499.75  5133884.00  11765810.75
31  2023  5413853.75  5330891.50  12408762.75
32  2024  5495144.75  5409691.25  13497184.00
33  2025   872336.25   860447.75   2356844.25

In [ ]:
# 연도 제외 수출 + 수입 + 환적 합계
result_data['합계'] = result_data[['수출', '수입', '환적']].sum(axis=1)

# 왼쪽 위의 '구분' 제거
result_data.columns.name = None

# 각 항목 비중
result_data['수출비중(%)'] = (result_data['수출'] / result_data['합계'] * 100).round(2)
result_data['수입비중(%)'] = (result_data['수입'] / result_data['합계'] * 100).round(2)
result_data['환적비중(%)'] = (result_data['환적'] / result_data['합계'] * 100).round(2)
result_data = result_data.set_index('연도')


result_data

,수출,수입,환적,합계,수출비중(%),수입비중(%),환적비중(%)
연도,,,,,,,
1992,1452695.00,1182679.00,0.00,2635374.00,55.12,44.88,0.00
1993,1540479.00,1400756.00,0.00,2941235.00,52.38,47.62,0.00
1994,1721176.00,1861341.00,0.00,3582517.00,48.04,51.96,0.00
1995,1912575.75,2177758.00,0.00,4090333.75,46.76,53.24,0.00
1996,2023501.00,2338534.00,0.00,4362035.00,46.39,53.61,0.00
1997,2196912.50,2614249.00,0.00,4811161.50,45.66,54.34,0.00
1998,2449246.75,2862064.75,0.00,5311311.50,46.11,53.89,0.00
1999,2471408.75,3189473.25,0.00,5660882.00,43.66,56.34,0.00
2000,2596600.75,3785717.00,0.00,6382317.75,40.68,59.32,0.00
2001,2558561.50,2571132.50,2943107.75,8072801.75,31.69,31.85,36.46
2002,2813530.75,2752573.25,3887984.00,9454088.00,29.76,29.12,41.12
2003,3061843.00,3095285.25,4251414.25,10408542.50,29.42,29.74,40.85
2004,3367405.00,3331520.00,4791840.00,11490765.00,29.31,28.99,41.70
2005,3315620.00,3348050.75,5179724.00,11843394.75,28.00,28.27,43.74
2006,3387969.25,3442844.00,5208295.25,12039108.50,28.14,28.60,43.26
2007,3693655.25,3756593.50,5811591.00,13261839.75,27.85,28.33,43.82
2008,3786886.25,3858055.75,5808188.00,13453130.00,28.15,28.68,43.17
2009,3327071.25,3280902.50,5372636.25,11980610.00,27.77,27.39,44.84
2010,3967771.75,3950133.25,6276690.75,14194595.75,27.95,27.83,44.22
2011,4372279.00,4460033.00,7352641.75,16184953.75,27.01,27.56,45.43
2012,4470118.25,4428513.25,8147545.75,17046177.25,26.22,25.98,47.80
2013,4512132.75,4425512.75,8748453.00,17686098.50,25.51,25.02,49.47
2014,4657638.75,4596289.75,9429354.75,18683283.25,24.93,24.60,50.47
2015,4650167.00,4713239.25,10105318.25,19468724.50,23.89,24.21,51.91
2016,4819338.75,4801126.50,9835826.00,19456291.25,24.77,24.68,50.55
2017,5159765.00,5055303.25,10278407.00,20493475.25,25.18,24.67,50.15
2018,5116408.50,5116858.50,11429309.00,21662576.00,23.62,23.62,52.76
2019,5162534.75,5191570.00,11637895.50,21992000.25,23.47,23.61,52.92
2020,4951252.75,4852616.75,12020125.50,21823995.00,22.69,22.24,55.08
2021,5225467.75,5207989.50,12272672.50,22706129.75,23.01,22.94,54.05
2022,5178499.75,5133884.00,11765810.75,22078194.50,23.46,23.25,53.29
2023,5413853.75,5330891.50,12408762.75,23153508.00,23.38,23.02,53.59
2024,5495144.75,5409691.25,13497184.00,24402020.00,22.52,22.17,55.31
2025,872336.25,860447.75,2356844.25,4089628.25,21.33,21.04,57.63