In [100]:
import pandas as pd
import numpy as np

PRO01_CSV_PATH = '../pro01.csv'

df = pd.read_csv(PRO01_CSV_PATH, encoding='cp949') #utf-8 or cp949

df

,연도,월,분기,청코드,내외항구분,수출입구분명,시설코드,시설명,부두구분명,아외국구분,적공구분,컨테이너수(10피트),컨테이너수(20피트),컨테이너수(40피트),컨테이너수(기타),전체개수,전체물동량
0,2024,3,1,신항,외항,수입,6,신항 W 정박지,일반부두,외국선,적컨,0,3,8,0,11,19.00
1,2024,4,2,신항,외항,수입,6,신항 W 정박지,일반부두,아국선,적컨,0,9,3,0,12,15.00
2,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,공컨,0,1,0,0,1,1.00
3,2024,11,4,신항,외항,수입,7,신항 U 정박지,일반부두,아국선,공컨,0,57,2,0,59,61.00
4,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,적컨,0,31,100,0,131,231.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2404,2024,7,3,북항,외항,수입환적,8,자성대 부두,컨테이너부두,외국선,적컨,0,8769,6434,0,15203,21637.00
2405,2024,7,3,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,7719,6438,2,14159,20599.50
2406,2024,7,3,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,7818,7253,0,15071,22324.00
2407,2024,11,4,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,2519,2018,3,4540,6561.75
2408,2024,11,4,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,4651,3613,0,8264,11877.00

In [101]:
pd.DataFrame({'자료형': df.dtypes.astype('str'),
              '비결측수': df.notna().sum(),
              '결측수': df.isna().sum(),
              '결측률(%)': df.isna().mean()*100,
              '고유값 수': df.nunique(dropna=True)})

                 자료형  비결측수  결측수  결측률(%)  고유값 수
연도             int64  2409    0     0.0      1
월              int64  2409    0     0.0     12
분기             int64  2409    0     0.0      4
청코드              str  2409    0     0.0      3
내외항구분            str  2409    0     0.0      1
수출입구분명           str  2409    0     0.0      4
시설코드           int64  2409    0     0.0     19
시설명              str  2409    0     0.0     30
부두구분명            str  2409    0     0.0      2
아외국구분            str  2409    0     0.0      2
적공구분             str  2409    0     0.0      2
컨테이너수(10피트)    int64  2409    0     0.0     62
컨테이너수(20피트)    int64  2409    0     0.0   1413
컨테이너수(40피트)    int64  2409    0     0.0   1617
컨테이너수(기타)      int64  2409    0     0.0    190
전체개수           int64  2409    0     0.0   1792
전체물동량        float64  2409    0     0.0   1938

In [102]:
col = df.columns.to_list
col

<bound method IndexOpsMixin.tolist of Index(['연도', '월', '분기', '청코드', '내외항구분', '수출입구분명', '시설코드', '시설명', '부두구분명',
       '아외국구분', '적공구분', '컨테이너수(10피트)', '컨테이너수(20피트)', '컨테이너수(40피트)',
       '컨테이너수(기타)', '전체개수', '전체물동량'],
      dtype='str')>

In [103]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
연도,2409.0,2024.000000,0.000000,2024.0,2024.0,2024.0,2024.00,2024.0
월,2409.0,6.593192,3.462982,1.0,4.0,7.0,10.00,12.0
분기,2409.0,2.529680,1.124354,1.0,2.0,3.0,4.00,4.0
시설코드,2409.0,11.799087,7.905031,1.0,8.0,9.0,14.00,31.0
컨테이너수(10피트),2409.0,2.574097,13.428490,0.0,0.0,0.0,0.00,132.0
컨테이너수(20피트),2409.0,2357.080531,3874.324901,0.0,44.0,407.0,3190.00,26277.0
컨테이너수(40피트),2409.0,3865.119967,7842.387127,0.0,84.0,889.0,3932.00,60733.0
컨테이너수(기타),2409.0,18.185969,54.339276,0.0,0.0,0.0,6.00,541.0
전체개수,2409.0,6242.960565,11470.764156,1.0,154.0,1381.0,7027.00,82897.0
전체물동량,2409.0,10129.522623,19308.235586,1.0,240.0,2316.5,11131.25,144125.0

In [104]:
data_cols = ['월', '수출입구분명','컨테이너수(20피트)', '컨테이너수(40피트)'] #원하는 수치만 선택

project = df[data_cols]

In [105]:
project['total'] = project['컨테이너수(20피트)'] + (project['컨테이너수(40피트)']*2)
project    #특이값(10피트,기타)제외한 합계

       월 수출입구분명  컨테이너수(20피트)  컨테이너수(40피트)  total
0      3     수입            3            8     19
1      4     수입            9            3     15
2     11   수입환적            1            0      1
3     11     수입           57            2     61
4     11   수입환적           31          100    231
...   ..    ...          ...          ...    ...
2404   7   수입환적         8769         6434  21637
2405   7     수출         7719         6438  20595
2406   7     수입         7818         7253  22324
2407  11     수출         2519         2018   6555
2408  11     수입         4651         3613  11877

[2409 rows x 5 columns]

In [106]:
project["수출입구분명"].unique().tolist()  #수출입 구분 고유값 추출

['수입', '수입환적', '수출환적', '수출']

In [107]:
project.loc[project['수출입구분명'] ==('수입환적' or '수출환적')]

       월 수출입구분명  컨테이너수(20피트)  컨테이너수(40피트)  total
2     11   수입환적            1            0      1
4     11   수입환적           31          100    231
7      3   수입환적          228         6675  13578
11     4   수입환적          556         1366   3288
15     8   수입환적          663         2065   4793
...   ..    ...          ...          ...    ...
2390  10   수입환적         2754         1864   6482
2394   2   수입환적         7707         6240  20187
2398   6   수입환적         9291         6775  22841
2402  11   수입환적         3128         2159   7446
2404   7   수입환적         8769         6434  21637

[618 rows x 5 columns]

In [108]:

result = []
for i in project["월"].unique().tolist():
    month_sum = project.loc[project['월'] == i ].sum()
    month_sum["월"] = i
    result.append(month_sum)
    
monthly_sum = pd.DataFrame(result)
monthly_sum = monthly_sum.sort_values("월")
result = monthly_sum[['월','total']]
result

     월    total
11   1  1983959
5    2  1869732
0    3  2136079
1    4  2037556
8    5  2088685
6    6  2082112
7    7  2098444
3    8  2044365
10   9  1869464
4   10  2041495
2   11  1989752
9   12  2058712

In [109]:
result_month = result.sort_values("월").set_index("월")

result_month["증감률(%)"] = (
    result["total"]
    .pct_change()
    .mul(100)
    .round(2)
)

result_month   #월별데이터분석,추세분석

      total  증감률(%)
월
1   1983959   -4.61
2   1869732   -2.53
3   2136079   -2.58
4   2037556    9.20
5   2088685   -5.76
6   2082112   -0.31
7   2098444    0.78
8   2044365    2.51
9   1869464    3.47
10  2041495   -8.56
11  1989752     NaN
12  2058712     NaN

In [110]:
season_map = {
    1: "겨울", 2: "겨울",
    3: "봄", 4: "봄", 5: "봄",
    6: "여름", 7: "여름", 8: "여름",
    9: "가을", 10: "가을", 11: "가을",
    12: "겨울"
}

result_month["계절"] = result_month.index.map(season_map)

season_result = (
    result_month
    .groupby("계절")["total"]
    .sum()
    .to_frame()
    .reindex(["봄", "여름", "가을", "겨울"])
)

season_result              #계절성 분석

      total
계절
봄   6262320
여름  6224921
가을  5900711
겨울  5912403

In [113]:
trans_result = project.pivot_table(
    index="월",
    columns="수출입구분명",
    values="total",
    aggfunc="sum",
    fill_value=0
)

trans_result["환적"] = trans_result["수입환적"] + trans_result["수출환적"]

trans_result = trans_result[["환적", "수입", "수출"]]

trans_result["총합"] = trans_result[["환적", "수입", "수출"]].sum(axis=1)

trans_result["환적비중(%)"] = (
    trans_result["환적"]
    .div(trans_result["총합"])
    .mul(100)
    .round(2)
)
trans_result.columns.name = None
trans_result #환적 비중

         환적      수입      수출       총합  환적비중(%)
월
1   1099847  427406  456706  1983959    55.44
2   1048160  400304  421268  1869732    56.06
3   1128652  522347  485080  2136079    52.84
4   1088207  468774  480575  2037556    53.41
5   1164386  459528  464771  2088685    55.75
6   1138905  476154  467053  2082112    54.70
7   1154651  457619  486174  2098444    55.02
8   1133873  455028  455464  2044365    55.46
9   1041513  417985  409966  1869464    55.71
10  1142957  430628  467910  2041495    55.99
11  1125503  420856  443393  1989752    56.56
12  1156427  460752  441533  2058712    56.17

In [114]:
trans_result.describe()

                 환적             수입             수출            총합    환적비중(%)
count  1.200000e+01      12.000000      12.000000  1.200000e+01  12.000000
mean   1.118590e+06  449781.750000  456657.750000  2.025030e+06  55.259167
std    4.089236e+04   32737.965775   24102.546603  8.432499e+04   1.122339
min    1.041513e+06  400304.000000  409966.000000  1.869464e+06  52.840000
25%    1.096937e+06  425768.500000  442928.000000  1.988304e+06  54.940000
50%    1.131262e+06  456323.500000  460738.500000  2.042930e+06  55.585000
75%    1.145880e+06  462757.500000  471076.250000  2.083755e+06  56.007500
max    1.164386e+06  522347.000000  486174.000000  2.136079e+06  56.560000